name: Workflow from actions

on:
  push:
    paths:
      - .github/workflows/workflow-from-actions.yml

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      ## Google Cloud
      - name: Login to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: Get Google Cloud's Kubernetes credentials
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'mlops-workshop'
          location: 'europe-west6-a'
      ## CML
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup CML
        uses: iterative/setup-cml@v1
      - name: Initialize runner on Kubernetes
        env:
          REPO_TOKEN: ${{ secrets.CML_PAT }}
        run: |
          export KUBERNETES_CONFIGURATION=$(cat $KUBECONFIG)
          # https://cml.dev/doc/ref/runner
          # https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#machine-type
          # https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#{cpu}-{memory}
          cml runner launch \
            --labels="cml-runner-from-actions" \
            --cloud="kubernetes" \
            --cloud-image="iterativeai/cml:0-dvc3-base1-gpu" \
            --cloud-type="1-2000" \
            --idle-timeout=1200 \
            --single

  use-runner:
    needs: setup-runner
    runs-on: [self-hosted, cml-runner-from-actions]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Node is required to run CML
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup CML
        uses: iterative/setup-cml@v1
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "It's a success!" >> report.md
          cml comment update --publish report.md
